---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность оформлять заказ
  - Пользователь должен иметь возможность просмотреть уже оформленные заказы
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность прелистывать страницы с товарами
  - Сайт должен быть разработан с учетом удобства использования на различных устройствах
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Имя пользователя при регистрации должно иметь не менее 4 и не более 25 символов
  - Пароль при регистрации должен иметь не менее 6 символов, включая 1 заглавную букву и символ "*+!"
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность оставаться авторизованным после перезагрузки страницы
